name: release
on:
  push:
    branches:
      - $default-branch
    tags:
      - 'v*.*.*'
  pull_request:
    types:
      - labeled

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    if: github.event.action != 'labeled'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Bump version on merging Pull Requests with specific labels.
      # (bump:major,bump:minor,bump:patch)
      - id: bumpr
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: haya14busa/action-bumpr@v1

      # Get tag name.
      - id: tag
        uses: haya14busa/action-cond@v1
        with:
          cond: "${{ startsWith(github.ref, 'refs/tags/') }}"
          if_true: ${{ github.ref }}
          if_false: ${{ steps.bumpr.outputs.next_version }}

      - name: Setup node
        if: "steps.tag.outputs.value != ''"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        if: "steps.tag.outputs.value != ''"
        uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        if: "steps.tag.outputs.value != ''"
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        if: "steps.tag.outputs.value != ''"
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        if: "steps.tag.outputs.value != ''"
        run: pnpm install --frozen-lockfile

      - name: Build the project
        if: "steps.tag.outputs.value != ''"
        run: pnpm build && cp -rv ./public/* ./dist/

      - name: Verify build output
        if: "steps.tag.outputs.value != ''"
        shell: bash
        run: |
          if [ ! -d "./dist" ]; then
            echo "Build failed: dist directory not found."
            exit 1
          else
            echo "Build succeeded! 🎉"
          fi

      - name: Compress
        if: "steps.tag.outputs.value != ''"
        uses: a7ul/tar-action@v1.2.0
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./dist
          # ./public
          outPath: dist.tar.gz

      - name: Release
        if: "!${{ startsWith(github.ref, 'refs/tags/') }}"
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.tag.outputs.value }}
          body: ${{ steps.bumpr.outputs.message }}
          files: dist.tar.gz
          generate_release_notes: true

      - name: Release
        if: "${{ startsWith(github.ref, 'refs/tags/') }}"
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.tag.outputs.value }}
          files: dist.tar.gz
          generate_release_notes: true

  release-check:
    permissions:
      contents: write
      pull-requests: write
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Post bumpr status comment
        uses: haya14busa/action-bumpr@v1
